spring:
 application:
  name: SoftWareCupSpring
 datasource:
  url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:software}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: ${DB_USER:root}
  password: ${DB_PASS:0515}
 servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB

mybatis:
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 开启驼峰映射,current_time->currentTime
  map-underscore-to-camel-case: true

aliyun:
 oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  bucketName: softwarecup2025
  region: cn-beijing

ai:
 flaskUrl: https://hz-t3.matpool.com:29367
