spring:
 application:
  name: SoftWareCupSpring
 datasource:
  url: jdbc:mysql://localhost:3306/software
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: '1234'
mybatis:
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 开启驼峰映射,current_time->currentTime
  map-underscore-to-camel-case: true

aliyun:
 oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  bucketName: softwarecupp
  region: cn-beijing
  accessKeyId: LTAI5tEzekfqvHsyM2XMt45R
  accessKeySecret: rDW2uJ8Wi7O71xHHNcrHX6K1LR5UZt


ai:
 flaskUrl: https://hz-4.matpool.com:28039
